version: "3.8"
services:
  code_server:
    image: vsc_ide
    container_name: vsc_ide
    user: root
    environment:
      - DOCKER_USER=$USER
      - ABSPATH=${ABSPATH}
    volumes:
      - ../apps/vsc_ide/app:/home/coder/project
      - ../apps/vsc_ide/config/coder/.config:/home/coder/.config
      - ../apps/vsc_ide/config/code_server:/root/.config/code-server
      - ../apps/vsc_ide/extensions:/root/.local/share/code-server/extensions
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    restart: unless-stopped
    networks:
      vsc_network:
        ipv4_address: ${VSC_IP}

networks:
  vsc_network:
    external: true